kernoeb/PlanningSup

static/url.json

Ajout support Université de Lille

---

assets/url.json
server/index.js

trop de modif pour tout lister

Mise à jour de SSI Lorient

---

assets/url.json

- Use of concatenation for the different promotion groups
- GEA modification
- Adding and deleting real alternating groups for BUT INFO

Update calendar for IUT Vannes

---

assets/url.json

Direct modification from the schedule list from ADE

Update calendar for SSI MIS - Vannes

---

assets/plannings.json

Update ENSIBS plannings

---

assets/plannings.json

Made changes for year 2022-2023

Update IUT de Saint-Malo

---

server/util/utils.js

Amélioration de la détection du type de cours (colorisation)
Principalement pour les plannings de l'INSA de Rennes, améliore également les plannings dont le groupe de TD/TP est spécifié en nom.
Ajout du remplacement de valeur pour les cours à distance de l'INSA de Rennes.

Amélioration de la détection du type de cours (colorisation)

---

assets/plannings.json

edt-pei1-lorient

---

assets/plannings.json

Bonjour,
Ceci est un fix pour l'issue #88 
Le script dans ressource semble avoir donné une mauvaise ID la première fois et le second semestre n'a pas été testé au préalable. 
Cette fois ci, l'ID a été testé et semble correcte.

Fix incorrect id for PEI 2 semester 2

---

assets/plannings.json

Ajouts des projets de M1 Info à l'ISTIC / univ rennes1.
Les modifications ont été créées par le script dans ressources/

add istic/m1info/projets

---

assets/plannings.json

Les plannings ont été vidés donc plus besoin de les avoir

Suppression du S5 de l'INSA de Rennes

---

assets/plannings.json

Corrections de typo INSA Rennes et suppression des plannings non utilisés

Update INSA Rennes

---

assets/plannings.json

Added LP DevOps planning from IUT Lyon 1

Update LP DevOps Lyon 1

---

assets/plannings.json

Ajout des mineures  du S6 pour les L3 info

Modification planning ISTIC

---

assets/plannings.json

Add INSA MA Planning

---

assets/plannings.json

Adds a specialty's timetables to this cool app :)
I tested all the timetables in local (using the dev compose file) and everything should be correct.
Thanks for making this it's way better than our school's app

Adds INSA Rennes - EII timetables

---

assets/plannings.json

Hello !
J'aimerais ajouter le planning du département GPM de l'INSA Rennes.
Il est susceptible de changer au cours de l'année.
Merci d'avance,
Bonne journée !

INSA Rennes GPM

---

package-lock.json
package.json
scripts/check-plannings-json.mjs

don't forget our dear windows users (me, ofc)

chore: add cross-env and fix plannings path for windows

---

assets/plannings.json

Depuis la rentrée ils ont ajouté des groupes de TP pour les options et les projets, ça doit tout remettre

Mise à jour du planning M1 IL Classique (ajout de projets et options)

---

assets/plannings.json

Bonjour :wave: 
J'ai mis les plannings pour ISTIC M1 IL Alternance à jour car les groupes ont été refaits, il n'y a plus de "alternance groupe 2" mais "classique groupe 2".

updated schedules for ISTIC M1 IL Alternance

---

assets/plannings.json

Hello !
J'ai ajouté le planning pour L2 Mathématique à l'Université de Rennes.
Il me semble que `projectId=2` est correct.
Merci :)

add: UFR Mathématique License 2

---

.idea/dataSources.local.xml
.idea/jsLibraryMappings.xml
components/DialogSettings.vue
components/HelpInfo.vue
components/TimezoneSelector.vue
layouts/default.vue
nuxt.config.js
pages/index.vue
server/routes/calendar.js
server/util/utils.js

#148 : Corrections de quelques bugs d'affichage

Timezone adjustments

---

assets/plannings.json

Bonjour, 
J'ai corrigé les ids de ressource des cyberdata du TP2 en 3A.
Bonne journée

Fix ressource planning of cyberdata TP2 S5-S6 

---

assets/plannings.json

Salut !
Mise à jour des EdT de Promo L1 PEI pour le S2
Merci encore pour ce projet qui nous permet d'avoir un emploi du temps bien plus optimisé.

Add: PEI-A 1ère Année S2

---

assets/plannings.json

Salut,
J'ai ajouté les calendrier des options de M1 IL.
Merci :)

Add M1 IL alternance options

---

assets/plannings.json

J'ai ajouté les calendrier des options et des mineurs de ISTIC M1 IL classiques.

Add ISTIC M1 classique options and minors

---

resources/plannings/mis-vannes.json

👋 Y'a eu une nouvelle présentation des plannings, autant mettre à jour toutes les filières

MAJ S1 et S2 de toutes les filières - MIS Vannes

---

resources/plannings/insa-rennes.json

Changes the IOT course to Robotics. The resource id didn't change so the url stays the same.
I tested locally and it works.

INSA Rennes INFO: Change IOT to Robotics

---

resources/plannings/insa-rennes.json

Should add timetables for first year + harmo but i can't test it since it requires a .env file in apps/web-apps and I can't find what is required to put inside.
I tested it when it was the big fat json files and it seems to work then.

add timetable for 1STPI (again)

---

resources/plannings/enscr.json

Cette PR ajoute les emplois du temps de l'ENSCR

Add enscr.json

---

resources/plannings/mis-vannes.json

👋 J'ai ajouté les groupes TEDS pour la L2 à Vannes

Ajout des groupes TEDS pour la L2 MIS Vannes
